# Generated by Django 4.2.17 on 2024-12-16 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('venta', 'venta'), ('alquiler', 'alquiler')], default='alquiler', max_length=8)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=14)),
                ('destino', models.CharField(choices=[('vivienda', 'vivienda'), ('comercial', 'comercial')], default='vivienda', max_length=9)),
                ('zona', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=90)),
                ('imagen', models.ImageField(upload_to='imagenes')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
