# Generated by Django 4.2.17 on 2024-12-16 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliariumwebsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='name',
            field=models.CharField(default='Inmueble', max_length=50),
        ),
    ]
