# Generated by Django 4.2.17 on 2024-12-30 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliariumwebsite', '0002_inmueble_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='InmuebleImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='galeria_inmuebles')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='inmobiliariumwebsite.inmueble')),
            ],
        ),
    ]
