# Generated by Django 4.2.17 on 2024-12-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliariumwebsite', '0003_alter_inmueble_descripcion_inmuebleimagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inmueble',
            old_name='imagen',
            new_name='imagen_destacada',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='destino',
        ),
        migrations.AddField(
            model_name='inmueble',
            name='area',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='bathrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='garage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='rooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='zona',
            field=models.CharField(choices=[('hawaii', 'Hawaii'), ('caribe', 'Caribe'), ('borabora', 'Bora bora'), ('islamargarita', 'Isla Margarita'), ('islasmaldivas', 'Islas Maldivas'), ('bahamas', 'Bahamas')], default='hawaii', max_length=13),
        ),
    ]
