# Generated by Django 4.2.17 on 2024-12-30 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliariumwebsite', '0004_rename_imagen_inmueble_imagen_destacada_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inmueble',
            old_name='bathrooms',
            new_name='banos',
        ),
        migrations.RenameField(
            model_name='inmueble',
            old_name='activo',
            new_name='disponible',
        ),
        migrations.RenameField(
            model_name='inmueble',
            old_name='rooms',
            new_name='piezas',
        ),
    ]
