# Generated by Django 4.2.17 on 2024-12-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliariumwebsite', '0005_rename_bathrooms_inmueble_banos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmuebleimagen',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='inmueble',
            name='es_destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='finalidad',
            field=models.CharField(choices=[('vivienda', 'vivienda'), ('comercial', 'comercial')], default='vivienda', max_length=9),
        ),
    ]
