# Generated by Django 4.2.17 on 2025-01-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliariumwebsite', '0006_remove_inmuebleimagen_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='zona',
            field=models.CharField(choices=[('hawaii', 'Hawaii'), ('caribe', 'Caribe'), ('borabora', 'Bora bora'), ('islamargarita', 'Isla Margarita'), ('islasmaldivas', 'Islas Maldivas'), ('bahamas', 'Bahamas'), ('ilha-grande', 'Ilha Grande')], default='hawaii', max_length=13),
        ),
    ]
