# Generated by Django 4.2.17 on 2025-01-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliariumwebsite', '0008_alter_inmueble_es_destacado_alter_inmueble_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='precio',
            field=models.DecimalField(decimal_places=2, help_text='Siempre en DOLARES', max_digits=14),
        ),
    ]
