# Generated by Django 4.2.17 on 2025-01-20 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliariumwebsite', '0009_alter_inmueble_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='area',
            field=models.IntegerField(default=0, help_text='En metros cuadrados'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='es_destacado',
            field=models.BooleanField(default=False),
        ),
    ]
