# Generated by Django 4.2.17 on 2025-02-01 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inmobiliariumwebsite', '0010_alter_inmueble_area_alter_inmueble_es_destacado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='zona',
            field=models.CharField(choices=[('hawaii', 'Hawaii'), ('caribe', 'Caribe'), ('borabora', 'Bora bora')], default='hawaii', max_length=13),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmobiliariumwebsite.inmueble')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'inmueble')},
            },
        ),
    ]
